##@TYPE: Machine
#@NAME: Engicam i.MX6ULL MircoGEA boards
#@SOC: i.MX6ULL
#@DESCRIPTION: Machine configuration for Engicam i.MX6ULL MicroGEA boards
#@MAINTAINER: <support@engicam.com>

MACHINEOVERRIDES =. "mx6:mx6ul:mx6ull:mx6ull-microdev:"

include conf/machine/include/imx-base.inc
include conf/machine/include/arm/armv7a/tune-cortexa7.inc

DELTA_KERNEL_DEFCONFIG="${UNPACKDIR}/kernel-config/*"

KERNEL_DEVICETREE += " \
	engicam/imx6ull-microgea-microdev.dtb \
	engicam/imx6ull-microgea-microdev-lcd7.dtb \
	engicam/imx6ull-microgea-microdev-rev3.dtb \
	engicam/imx6ull-microgea-loco5.dtb \
"

# Double check the choice is consistent with Secure Boot/fitImage enablement
UBOOT_CONFIG ??= " sd "
UBOOT_CONFIG[sd]	= "microgea_mx6ull_sd_defconfig,sdcard"
UBOOT_CONFIG[nand]	= "microgea_mx6ull_nand_defconfig,ubifs"

IMAGE_FSTYPES += "ubifs"

# Enable free --space-fixup (-F) by default, this allows DFU updates
MKUBIFS_ARGS = "-m 4096 -e 248KiB -c 1596"
UBINIZE_ARGS = "-m 4096 -p 256KiB -s 4096"
UBI_VOLNAME = "nandrootfs"

MACHINE_FEATURES += "wifi bluetooth nxp8987-sdio"
MACHINE_FIRMWARE:append = " linux-firmware-bcm4373 linux-firmware-bcm43430"
