#@TYPE: Machine
#@NAME: MX8ULP MicroGEA
#@SOC: i.MX8ULP
#@DESCRIPTION: Machine configuration for Engicam MX8ULP MicroGEA boards
#@MAINTAINER: Engicam <support@engicam.com>

require include/imx8ulp.inc

DELTA_KERNEL_DEFCONFIG="${UNPACKDIR}/kernel-config/*"

KERNEL_DEVICETREE:append:use-nxp-bsp = " \
	engicam/imx8ulp-microgea-microdev-lcd7.dtb \
	engicam/imx8ulp-microgea-microdev-rev3.dtb \
	engicam/imx8ulp-microgea-loco5.dtb \
"

UBOOT_CONFIG_BASENAME = "imx8ulp_microgea"

MACHINE_FEATURES += "soc-reva1"
UPOWER_FIRMWARE_NAME = "upower_a1.bin"
IMX_DEFAULT_BSP = "nxp"
