#@TYPE: Machine
#@NAME: Engicam SmarCore MX8M Plus board
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for Engicam SmarCore MX8MP SOM + XTOUCH 2.0 board
#@MAINTAINER: <support@engicam.com>

require include/imx8mp-engicam.inc

DELTA_KERNEL_DEFCONFIG="${UNPACKDIR}/kernel-config/*"

# NXP kernel has additional DTB files for various board configuration and
# derivates. Include them here for NXP BSP only
KERNEL_DEVICETREE += " \
	engicam/imx8mp-smarcore-xtouch2.dtb \
"

UBOOT_DTB_NAME = "imx8mp-smarcore.dtb"

UBOOT_CONFIG_BASENAME = "imx8mp_smarcore"
UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "${UBOOT_CONFIG_BASENAME}_defconfig,sdcard"


# Set DDR FIRMWARE
DDR_FIRMWARE_VERSION = "202006"
DDR_FIRMWARE_NAME = " \
	lpddr4_pmu_train_1d_dmem_${DDR_FIRMWARE_VERSION}.bin \
	lpddr4_pmu_train_1d_imem_${DDR_FIRMWARE_VERSION}.bin \
	lpddr4_pmu_train_2d_dmem_${DDR_FIRMWARE_VERSION}.bin \
	lpddr4_pmu_train_2d_imem_${DDR_FIRMWARE_VERSION}.bin \
"

IMXBOOT_TARGETS_BASENAME = "flash_evk"

# Mainline BSP doesn't support LPDDR4 so it must be set to nxp.
# Also this machine isn't supported by u-boot-fslc but imx8mn-evk.inc already
# set the bootloader to u-boot-imx instead when NXP BSP is used.
IMX_DEFAULT_BSP = "nxp"
