#@TYPE: Machine
#@NAME: NXP i.MX 95 19x19 Evaluation Kit with LPDDR5
#@SOC: i.MX95
#@DESCRIPTION: Machine configuration for NXP i.MX 95 19x19 EVK with LPDDR5
#@MAINTAINER: Jun Zhu <junzhu@nxp.com>

MACHINEOVERRIDES =. "mx95:mx95-smarcore:"
MACHINE_FEATURES:remove = "nxpwifi-all-pcie nxpwifi-all-sdio"

require conf/machine/include/imx95-engicam.inc

DELTA_KERNEL_DEFCONFIG="${UNPACKDIR}/kernel-config/*"

KERNEL_DEVICETREE:append:use-nxp-bsp = " \
    engicam/imx95-smarcore-smarcore-evb.dtb \
    engicam/imx95-smarcore-xtouch2.dtb \ 
    engicam/imx95-smarcore-multimedia-4k.dtb \     
"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "imx95_smarcore_defconfig,sdcard"
#UBOOT_CONFIG[sd] = "imx95smarc"

IMXBOOT_TARGETS_BASENAME = "flash"
OEI_BOARD  = "mx95lp5"
DDR_TYPE   = "lpddr5"
IMX_SOC_REV:${MACHINE} = "B0"
#IMX_SOC_REV:${MACHINE} = "A0"

OEI_DDR_CONFIG = "lpddr5_4gb_6400mts_train_timing"
SYSTEM_MANAGER_CONFIG = "mx95evk"

DDR_FIRMWARE_NAME = " \
    lpddr5_dmem_v202409.bin \
    lpddr5_dmem_qb_v202409.bin \
    lpddr5_imem_v202409.bin \
    lpddr5_imem_qb_v202409.bin \
"

M4_DEFAULT_IMAGE_MX95 = "${@bb.utils.contains('SYSTEM_MANAGER_CONFIG', 'mx95netc', 'imx95-19x19-evk_m7_TCM_netc_share.bin', \
                                                                                   'imx95-19x19-evk_m7_TCM_power_mode_switch.bin', d)}"

PREFERRED_PROVIDER_wpa-supplicant = "summit-supplicant"
PREFERRED_RPROVIDER_wpa-supplicant = "summit-supplicant"
PREFERRED_RPROVIDER_wpa-supplicant-cli = "summit-supplicant"
PREFERRED_RPROVIDER_wpa-supplicant-passphrase = "summit-supplicant"
PREFERRED_RPROVIDER_wireless-regdb-static = "wireless-regdb"
