#@TYPE: Machine
#@NAME: Engicam MicroGEA MX91 boards with LPDDR4
#@SOC: i.MX91
#@DESCRIPTION: Machine configuration for Engicam MicroGEA MX91 boards with LPDDR4
#@MAINTAINER: support <support@engicam.com>

MACHINEOVERRIDES =. "mx91:imx91-icore:imx91-microdev:"

require conf/machine/include/imx91-engicam.inc

DELTA_KERNEL_DEFCONFIG="${UNPACKDIR}/kernel-config/*"

KERNEL_DEVICETREE += " \
    engicam/imx91-microgea-evb.dtb \
    engicam/imx91-microgea-loco5.dtb \
    engicam/imx91-microgea-microdev2-yes7.dtb \
    engicam/imx91-microgea-microdev2.dtb \
    engicam/imx91-microgea-microdev3.dtb \
    engicam/imx91-microgea-starterkit.dtb \
"

UBOOT_CONFIG_BASENAME = "imx91_microgea"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "${UBOOT_CONFIG_BASENAME}_defconfig,sdcard"

DDR_FIRMWARE_NAME = " \
    lpddr4_dmem_1d_v202201.bin \
    lpddr4_dmem_2d_v202201.bin \
    lpddr4_imem_1d_v202201.bin \
    lpddr4_imem_2d_v202201.bin \
"
