#@TYPE: Machine
#@NAME: NXP i.MX 91 11x11 Evaluation Kit with LPDDR4
#@SOC: i.MX91
#@DESCRIPTION: Machine configuration for NXP i.MX 91 11x11 EVK with LPDDR4
#@MAINTAINER: Jun Zhu <junzhu@nxp.com>

MACHINEOVERRIDES =. "mx91:"

require include/imx91-engicam.inc

KERNEL_DEVICETREE_BASENAME = "imx91-microgea"

KERNEL_DEVICETREE:append:use-nxp-bsp = " \
	engicam/${KERNEL_DEVICETREE_BASENAME}-starterkit.dtb \
	engicam/${KERNEL_DEVICETREE_BASENAME}-microdev3.dtb \
	engicam/${KERNEL_DEVICETREE_BASENAME}-microdev2.dtb \
"

# engicam/${KERNEL_DEVICETREE_BASENAME}-microdev2.dtb

UBOOT_CONFIG_BASENAME = "imx91_microgea"
#UBOOT_CONFIG_BASENAME = "imx91_11x11_evk"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "${UBOOT_CONFIG_BASENAME}_defconfig,sdcard"


DDR_FIRMWARE_NAME = " \
	lpddr4_dmem_1d_v202201.bin \
	lpddr4_dmem_2d_v202201.bin \
	lpddr4_imem_1d_v202201.bin \
	lpddr4_imem_2d_v202201.bin \
"

ENGICAM_KERNEL_CONFIG_AARCH64 = "imx91_microgea_defconfig"
