#@TYPE: Machine
#@NAME: NXP i.MX 95 19x19 Evaluation Kit with LPDDR5
#@SOC: i.MX95
#@DESCRIPTION: Machine configuration for NXP i.MX 95 19x19 EVK with LPDDR5
#@MAINTAINER: Jun Zhu <junzhu@nxp.com>

MACHINEOVERRIDES =. "mx95:mx95-icore:"

require include/imx95-engicam.inc

ENGICAM_KERNEL_CONFIG_AARCH64 = "imx95_icore_defconfig"
KERNEL_DEVICETREE:append:use-nxp-bsp = " \
    engicam/imx95-icore-starterkit.dtb \
"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "imx95_icore_defconfig,sdcard"

IMXBOOT_TARGETS_BASENAME = "flash"
OEI_BOARD  = "mx95lp5"
DDR_TYPE   = "lpddr5"
DDR_CONFIG   = "lpddr5_4gb_3200mts_train_timing"

DDR_FIRMWARE_NAME = " \
    lpddr5_dmem_v202311.bin \
    lpddr5_dmem_qb_v202311.bin \
    lpddr5_imem_v202311.bin \
    lpddr5_imem_qb_v202311.bin \
"
M4_DEFAULT_IMAGE_MX95 = "${@bb.utils.contains('SYSTEM_MANAGER_CONFIG', 'mx95netc', 'imx95-19x19-evk_m7_TCM_netc_share.bin', \
                                                                                   'imx95-19x19-evk_m7_TCM_power_mode_switch.bin', d)}"
PREFERRED_RPROVIDER_wpa-supplicant = "summit-supplicant-lwb-if"
PREFERRED_RPROVIDER_wpa-supplicant-cli = "summit-supplicant-lwb-if"
PREFERRED_RPROVIDER_wpa-supplicant-passphrase = "summit-supplicant-lwb-if"
PREFERRED_RPROVIDER_wireless-regdb-static = "wireless-regdb"
