#@TYPE: Machine
#@NAME: Engicam i.Core MX93 boards with LPDDR4X
#@SOC: i.MX93
#@DESCRIPTION: Machine configuration for Engicam i.Core MX93 boards with LPDDR4X
#@MAINTAINER: <support@engicam.com>

require conf/machine/include/imx93-engicam.inc

DELTA_KERNEL_DEFCONFIG="${UNPACKDIR}/kernel-config/*"

KERNEL_DEVICETREE += " \
        engicam/imx93-icore-ctouch2-amp10.dtb \
        engicam/imx93-icore-ctouch2.dtb \
        engicam/imx93-icore-ctouch3.1-yes7.dtb \
        engicam/imx93-icore-ctouch3.1.dtb \
        engicam/imx93-icore-starterkit.dtb \
"

UBOOT_CONFIG_BASENAME = "imx93_icore"
UBOOT_CONFIG ??= "2gb"
UBOOT_CONFIG[1gb] = "${UBOOT_CONFIG_BASENAME}_1gb_defconfig,sdcard"
UBOOT_CONFIG[2gb] = "${UBOOT_CONFIG_BASENAME}_defconfig,sdcard"

IMXBOOT_TARGETS_BASENAME = "flash_singleboot"

DDR_FIRMWARE_NAME = " \
    lpddr4_dmem_1d_v202201.bin \
    lpddr4_dmem_2d_v202201.bin \
    lpddr4_imem_1d_v202201.bin \
    lpddr4_imem_2d_v202201.bin \
"

UBOOT_CONFIG[fspi]   = "${UBOOT_CONFIG_BASENAME}_defconfig"

IMXBOOT_TARGETS = "${@bb.utils.contains('UBOOT_CONFIG', 'fspi', '${IMXBOOT_TARGETS_BASENAME}_flexspi', '${IMXBOOT_TARGETS_BASENAME}', d)}"
